// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVNv1NirUZPZ6L2Mj9bzQtvBiITauGPHk',
    appId: '1:925429520433:web:d393fa692ca2a7f6051d10',
    messagingSenderId: '925429520433',
    projectId: 'gocaffauth',
    authDomain: 'gocaffauth.firebaseapp.com',
    storageBucket: 'gocaffauth.firebasestorage.app',
    measurementId: 'G-SHVD4V6YYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByARbq2KdJXxL4JCRq2sm9EC7NXtkXjNY',
    appId: '1:925429520433:android:77809324abbb3f0d051d10',
    messagingSenderId: '925429520433',
    projectId: 'gocaffauth',
    storageBucket: 'gocaffauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPmWiwo2Mjs6Uf9lzgcWgufHVKRsOYSCk',
    appId: '1:925429520433:ios:e8d57d7b7bab5e03051d10',
    messagingSenderId: '925429520433',
    projectId: 'gocaffauth',
    storageBucket: 'gocaffauth.firebasestorage.app',
    iosBundleId: 'com.example.gocaff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPmWiwo2Mjs6Uf9lzgcWgufHVKRsOYSCk',
    appId: '1:925429520433:ios:e8d57d7b7bab5e03051d10',
    messagingSenderId: '925429520433',
    projectId: 'gocaffauth',
    storageBucket: 'gocaffauth.firebasestorage.app',
    iosBundleId: 'com.example.gocaff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVNv1NirUZPZ6L2Mj9bzQtvBiITauGPHk',
    appId: '1:925429520433:web:bd6ad92b6a15eada051d10',
    messagingSenderId: '925429520433',
    projectId: 'gocaffauth',
    authDomain: 'gocaffauth.firebaseapp.com',
    storageBucket: 'gocaffauth.firebasestorage.app',
    measurementId: 'G-L05E694CGJ',
  );
}
